# Generated by Django 4.1.1 on 2022-11-22 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='remainingStar',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='books',
            name='totalStar',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='stars',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
