# Generated by Django 4.1.1 on 2022-11-22 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0002_books_remainingstar_books_totalstar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='remainingStar',
        ),
        migrations.RemoveField(
            model_name='books',
            name='totalStar',
        ),
    ]
